[workspace]
resolver        = "2"
members         = ["remote-desk*"]
default-members = ["remote-desk-slint", "remote-desk-flutter"]

[profile.dev]
debug = 0

[profile.release]
codegen-units = 1
lto           = true
panic         = "abort"
strip         = true

[workspace.dependencies]
anyhow     = "1.0"
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio      = { version = "1.39", features = ["fs", "macros", "rt-multi-thread", "time"] }

remote-desk-config  = { path = "remote-desk-config" }
remote-desk-core    = { path = "remote-desk-core" }
remote-desk-infra   = { path = "remote-desk-infra" }
remote-desk-tools   = { path = "remote-desk-tools" }
remote-desk-flutter = { path = "remote-desk-flutter" }
remote-desk-slint   = { path = "remote-desk-slint" }
