[package]
name        = "remote-desk-core"
version     = "0.1.0"
edition     = "2021"
license     = "GPL"
authors     = ["zooeywm <zooeywm@gmail.com>"]
description = "remote-desk domain core"
repository  = "https://github.com/zooeywm/remote-desktop-rs"

[dependencies]
tokio  = { workspace = true }
